# Generated by Django 3.1.7 on 2021-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Message', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
