# Generated by Django 3.2.2 on 2021-05-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Subject',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='Kampala', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='description',
            field=models.TextField(default='test desc', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='gilo@gmail.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='Gilo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default='0776767868', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='topic',
            field=models.CharField(default='github', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
    ]
